name: jvc-electro-estilo-front

services:
  jvc-electro-estilo-front:
    build: .
    container_name: jvc-electro-estilo-front
    restart: always
    ports:
      - "3002:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=https://yirehapi.jvcsoluciones.cloud/api
